### ISSUE TITLE
Invalid expression Greylog 3.0.2+1686930

### ISSUE THREAD

**Issue by sadshade** [Graylog2/graylog-guide-snort#5]
Got error when create a rule "Invalid expression line 5 col 51"

let m = regex("let m = regex("^\\s?\\[(\\d+):(\\**\d**+):(\\d+)\\] (.+?)

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
